# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BatteryReminder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
       environment:
          description: 'Environment'
          type: environment
          default: 'xy_model3'
          required: true 

jobs:
  
  build:

    runs-on: ubuntu-latest
    
    env:
      TESLA_ACCESS_TOKEN: ${{ secrets.TESLA_ACCESS_TOKEN }}
      TESLA_REFRESH_TOKEN: ${{ secrets.TESLA_REFRESH_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node -v
    - run: echo ${{ github.event.inputs.environment }}
    - run: npm run teslac
